from datetime import datetime


class Logger:
    """
    Logs events generated by the application.
    """

    def info(self, message: str) -> None:
        self._log("INFO", message)

    def warning(self, message: str) -> None:
        self._log("WARNING", message)

    def error(self, message: str) -> None:
        self._log("ERROR", message)

    def _log(self, level: str, message: str) -> None:
        timestamp = datetime.now().strftime("%H:%M:%S")

        print(f"[{timestamp}] [{level}] {message}")